default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: bug_tracker_dev

test:
  <<: *default
  database: bug_tracker_test

production:
  <<: *default
  database: bug_tracker_prod
